### ISSUE TITLE
how create two synced picker side by side

### ISSUE THREAD

**Issue by AhmadVatani** [DavidPizarro/PickerUI#2]
I want to creat country picker with postal code and name of country. what can i do?
how can i use two picker side by side??

**Comment by DavidPizarro** [comment]
Hi!

Do you have an image to explain me what do you want exactly? Thanks!

**Comment by AhmadVatani** [comment]
I want to create like this, two row with different style for selected item:

![screen shot 2015-10-19 at 1 36 27 pm](https://cloud.githubusercontent.com/assets/13574768/10575008/7cfe831a-7666-11e5-8544-578051aa3e92.png)

**Comment by DavidPizarro** [comment]
Hi!

No, it is not possible to do that exactly with the library. But with the new version I have uploaded yesterday  **`- compile 'com.github.davidpizarro:pickerui:1.0.1' -`** you can use an alternative.

**Now you can know when is showing PickerUI panel.** See [#Changelog](https://github.com/DavidPizarro/PickerUI/blob/master/CHANGELOG.md)
In addition **`PickerUI`** object can be assigned to multiple components simultaneously, each with a different ID. Example:

``` java

private static final int CITY_ID = 0;
private static final int POSTAL_ID = 1;

private PickerUI mPickerUI;

llCity.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
             mPickerUI.setItems(MainActivity.this, cities, CITY_ID, 0);
             if (!mPickerUI.isPanelShown())
                 mPickerUI.slide();
         }
      });

llPostal.setOnClickListener(new View.OnClickListener() {
         @Override
         public void onClick(View v) {
             mPickerUI.setItems(MainActivity.this, postals, POSTAL_ID, 0);
             if (!mPickerUI.isPanelShown())
                 mPickerUI.slide();
         }
     });

mPickerUI.setOnClickItemPickerUIListener(new PickerUI.PickerUIItemClickListener() {
            @Override
            public void onItemClickPickerUI(int ID, int position, String valueResult) {
                switch (which){
                    case CITY_ID:
                        tvCity.setText(valueResult);
                        break;

                    case POSTAL_ID:
                        tvPostal.setText(valueResult);
                        break;
                }
            }
        });
```

So you can get the next results:

![Example gif](https://raw.githubusercontent.com/DavidPizarro/PickerUI/master/art/issue_2_3.gif)

You can download an example with this functionality [here](http://www.davidpizarro.es/github/SomePickersUI.zip).

I hope that will be helpful!
