### ISSUE TITLE
background problem

### ISSUE THREAD

**Issue by 1455726533** [DavidPizarro/PickerUI#4]
its background turns to black when sliding

maybe you need add this:"cacheColorHint" for your custom Listview

**Comment by DavidPizarro** [comment]
Sorry, could you explain me what was the error?
Do you propose to use cacheColorHint in the library?

Thanks!

**Comment by 1455726533** [comment]
sorry,it's my fault, i just want to change the cachaColorHint for my test
app,then I find it in yout libs ,thanks for your reply !!!

2015-11-10 22:35 GMT+08:00 David Pizarro notifications@github.com:
