### ISSUE TITLE
Attribute conflict

### ISSUE THREAD

**Issue by jairook** [DavidPizarro/PickerUI#9]
Hello,
When i include your library in my gradle file, it gives error while syncing...

Error:(2) Attribute "entries" has already been defined

I cannot figure out what is causing this problem. Please Help!!

**Comment by azrashaikh** [comment]
How you included this project as gradle ?
I am not able to do this : 
 `compile 'com.github.davidpizarro:pickerui:1.0.1'`

**Comment by jairook** [comment]
Hello Azra,  
your method should work!  
When i first included this library it didn't seem to work, but give it a little time for Gradle Sync..It should work..  
In my case problem arose because i was having some problem with the attributes...  
But, still if you want to include this project in a different way, you can just download the whole source code and use 'Import Library' feature of the Android Studio to include the library sub directory of the downloaded project. After that, you just need to update the line in settings.gradle file from

**include ':app'** to **include ':app', ':library'**

And then you can use the library!!

**Comment by dhruv3011** [comment]
How can I change the TextView textSize? Is there any method or not?

**Comment by jairook** [comment]
You can change the textSize by using  
'<pickerui:textCenterColor="#
pickerui:textNoCenterColor="#737373">'

**Comment by jairook** [comment]
Hello Dhruv,
This guy has not provided any kind of attribute to change text size of the PickerUI. But I suggest you try using the inbuilt android attributes **textSize** and check. 
If that does not help, then I am afraid you cannot do anything if you are including this library using compile method. But if you are importing this library in the form of a module in your project, then you can go inside the Java files and make a **getTextSize()** function by yourself, in which you can call the textSize from inside.  
This way it can be done!!

**Comment by jairook** [comment]
The 'entries' attribute has been already used in a different library, that is why i was getting that error.  
So, either you can edit the source code by yourself and make the changes or  
change the library that is using the same attribute or  
just use download the whole source code and import the code as library explicitly.

I hope this helps.:P
